config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :questions do
    resources :answers
  end
  resources :sessions
  resources :votes
  resources :best_answers
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes
  has_one :best_answer
  validates :answer, presence: true

  # scope :best_answer, -> { where(best_answer: true) }

  # def make_answer_best
  #   question = self.question
  #   question.answers.each {|answer| answer.best_answer = false)}
  #   self.best_answer = true
  # end
end

app/models/best_answer.rb
class BestAnswer < ActiveRecord::Base
  belongs_to :answer
  belongs_to :question
  validates_uniqueness_of :answer_id
  validates_uniqueness_of :question_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :title, presence: true
  validates :question, presence: true

  # def answers_order
  #   final_order = []
  #   final_order << self.answers.best_answer.first
  #   order_array = self.answers.sort { |a, b| b.votes.count <=> a.votes.count}
  #   order_array.map {|answer| final_order << answer if !answer.best_answer  }
  #   final_order
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :votes
  has_secure_password
  validates_uniqueness_of :email
  validates_presence_of :email
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  def show
    @answer = Answer.find(params[:id])
    @best_answer = BestAnswer.new
  end

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
    render 'new.js.erb'
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      respond_to do |format|
        format.html { redirect_to :back}
        format.js
      end
      flash[:notice] = "Your answer was added."
    else
      render "question/#{@question.id}"
    end
  end

  def destroy
    @answer = Answer.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:answer)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not authorized!" if current_user.nil?
    end
end

app/controllers/best_answers_controller.rb
class BestAnswersController < ApplicationController
  def new
    @best_answer = BestAnswer.new
  end

  def create
    @best_answer = BestAnswer.new(best_answer_params)
    if @best_answer.save
      flash[:notice] = "Best answer was added."
      redirect_to :back
    else
      render 'new'
    end
  end

  private
    def best_answer_params
      params.require(:best_answer).permit(:answer_id, :question_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.all
    @best_answer = BestAnswer.new
    @answer = Answer.new
    @vote = Vote.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "#{@question.title} was added. Thanks for asking!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "#{@question.title} updated."
      redirect_to question_path(@question)
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "The question was deleted."
      redirect_to root_path
    end
  end

private
    def question_params
      params.require(:question).permit(:title, :question)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:notice] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.email} was added. Thanks for signing up!"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "#{@user.email} updated."
      redirect_to users_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = user.find(params[:id])
    if @user.destroy
      flash[:notice] = "The user was deleted."
      redirect_to users_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      flash[:notice] = "Vote was added."
      redirect_to :back
    else
      render 'new'
    end
  end

  private
    def vote_params
      params.require(:vote).permit(:user_id, :answer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<div id="answer_<%= answer.id %>" class="row">
  <div class="col-md-1">

  </div>
  <div class="col-md-8">
    <p>
      <%= answer.answer %>, <%= answer.created_at.strftime("%A %b %d, %Y %l:%M %p") %>
      Votes: <%= answer.votes.count %>
      <% if current_user == @question.user %>
        <%= link_to "(remove)", question_answer_path(@question, answer), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
      <% end %>
    </p>
  </div>
</div>

app/views/answers/_form.html.erb
<%= form_for ([@question, @answer]), remote: true do |f| %>

  <%= render("layouts/errors", :object => @answer) %>

  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer, :size => "50x5" %>
  </div>
  <div class="actions">
    <%= f.submit(:class => "btn btn-success btn-xs") %>
  </div>
<% end %>

app/views/answers/create.js.erb
$('#new_answer').remove();
$('#new_link').show();
$('#answer_list').append('<%= j render(@answer) %>');
$('#edit_answer_<%= @answer.id %>')

app/views/answers/destroy.js.erb
$('#answer_<%= @answer.id %>').remove();

app/views/best_answers/create.js.erb
$('#edit_best_answer_<%= @best_answer.id %>')

app/views/best_answers/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack Overflow Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <nav class="navbar navbar-inverse fixed navbar-custom" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav title">
          <li><%= link_to "StackExchange", root_path %></li>
          <% if current_user %>
            <li><%= link_to "New Question", new_question_path %></li>
            <li><%= link_to "Log out", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
      </ul>
    </div>
  </nav>
<body>
  <div class="container">
    <% if current_user %>
      <p>Logged in as <%= current_user.email %></p>
    <% end %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

  <%= render("layouts/errors", :object => @question) %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question, :size => "50x5" %>
  </div>
  <div class="actions">
    <%= f.submit(:class => "btn btn-success btn-xs") %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
    <p><%= question.user.email %></p>
    <p><%= link_to question.title, question_path(question) %></p>
    <p><%= question.created_at.strftime("%A %b %d, %Y %l:%M %p") %></p>
<% end %>

app/views/questions/new.html.erb
<h1>Ask Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="strong">
  <p><%= @question.user.email %></p>
  <p><%= @question.title %></p>
  <p><%= @question.question %></p>
  <p><%= @question.created_at.strftime("%A %b %d, %Y %l:%M %p") %></p>
</div>

<div class="row">
  <div class="col-md-1">
    <p>Best Answer</p>
  </div>
</div>

<div class="answers" id="answer_list">
  <%= render @question.answers %>
</div>

<% if current_user == @question.user %>
  <p><%= link_to "Edit", edit_question_path(@question), :class => "btn btn-default" %></p>
  <p><%= link_to "Delete", question_path(@question),
                           :data => {:confirm => "You sure?",
                                     :method => "delete"},
                           :class => "btn btn-danger" %></p>
<% end %>

<% if current_user %>
  <%= link_to "Answer Question", new_question_answer_path(@question, @answer), id: "new_link", remote: true %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit(:class => "btn btn-success btn-xs") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Current Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %> </td>
        <td><%= link_to 'Edit', edit_user_path(user) %> </td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>My photos</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.photo.url(:thumb) %>"<%= photo.name %>", Created at: <%= photo.created_at.strftime("%A %b %d, %Y %l:%M %p") %></td>
    <% end %>
  </tbody>
</table>